# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: xenial
services:
  - docker
language: generic
compiler:
  - gcc

before_install: # Use this to prepare the system to install prerequisites or dependencies
  # Define some config vars
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - pwd
  - ls -la
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
  - sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-rosdep python-wstool python-catkin-tools python-catkin-pkg
  # Setup rosdep
  - sudo rosdep init
  - rosdep update
  
install:
  - sudo apt-get update
  - sudo pip install coveralls
  - sudo apt-get install ros-$ROS_DISTRO-desktop-full
  - source /opt/ros/$ROS_DISTRO/setup.bash
  # - mkdir -p ~/catkin_ws/src
  # - cd ~/catkin_ws/src
  # - catkin_init_workspace
  # # Create the devel/setup.bash (run catkin_make with an empty workspace) and
  # # source it to set the path variables.
  # - cd ~/catkin_ws
  # - catkin_make
  # - source devel/setup.bash
  # # Add the package under integration to the workspace using a symlink.
  # - cd ~/catkin_ws/src
  # - ln -s $CI_SOURCE_PATH .

notifications:
  email:
    recipients:
      - subhasdaas@gmail.com
env:
  matrix:
    - ROS_DISTRO=kinetic  ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=./example_ros_pkg.rosinstall
# before_script:
  # - git clone -q https://github.com/bailaC/moveit_ci.git .moveit_ci
  
before_script:
  # source dependencies: install using wstool.
  #- cd ~/catkin_ws/src
  - wstool init
  - if [[ -f $ROSINSTALL_FILE ]] ; then wstool merge $ROSINSTALL_FILE ; fi
  - wstool up
  # package depdencies: install using rosdep.
  #- cd ~/catkin_ws
  #- rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO
  - git clone -q https://github.com/bailaC/moveit_ci.git .moveit_ci

script:
  - source .moveit_ci/travis.sh

after_success:
  - source /opt/ros/$ROS_DISTRO/setup.bash
  #- cd ~/catkin_ws
  #- catkin_make $( [ -f $CATKIN_OPTIONS ] && cat $CATKIN_OPTIONS )
  # Run the tests, ensuring the path is set correctly.
  #- source devel/setup.bash
  #- catkin_make run_tests && catkin_test_results
  - rostest ros_test test/ros_test.test
  - coveralls